x_bsystem_wirecard_checkout:
    path: /checkout/
    defaults: { _controller: XBsystemWirecardBundle:Checkout:index }

x_bsystem_wirecard_genform:
    path: /wirecard/genform/
    defaults: { _controller: XBsystemWirecardBundle:Checkout:genform }

x_bsystem_wirecard_ajax_genform:
    path: /wirecard/ajax/genformajax/
    defaults: { _controller: XBsystemWirecardBundle:Checkout:genformajax }

x_bsystem_wirecard_handleresponse:
    path: /wirecard/handleresponse/
    defaults: { _controller: XBsystemWirecardBundle:Checkout:handleresponse }
